apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: python-example
spec:
  image: { ACOUNT NUMBER }.dkr.ecr.{ REGION }.amazonaws.com/flink-1.18.0-uber-jar:0.1
  imagePullPolicy: Always
  flinkVersion: v1_18
  ingress:
    template: "*/"
    className: "alb"
  executionRoleArn: arn:aws:iam::{ ACCOUNT ID }:role/emr-eks-job-execution-FLINK-ROLE
  emrReleaseLabel: "emr-7.0.0-flink-latest"
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "1"
  jobManager:
    storageDir: s3://{ BUCKET }/jobmanager/
    resource:
      memory: "4096m"
      cpu: 2
  taskManager:
    resource:
      memory: "4096m"
      cpu: 2
  job:
    jarURI: s3://{ BUCKET }/scripts/flink_kinesis_kdg.py
    entryClass: "org.apache.flink.client.python.PythonDriver"
    args: ["-py", "/opt/flink/usrlib/flink_kinesis_kdg.py", "--bucket", "{ BUCKET }", "--streamName", "{ STREAM NAME }"]
    parallelism: 2
    upgradeMode: stateless
  monitoringConfiguration:
    image: { ACCOUNT ID }.dkr.ecr.{ REGION }.amazonaws.com/emr-7.0.0-fluentd:0.1
    cloudWatchMonitoringConfiguration:
       logGroupName: /aws/emr-eks/flink
